name: cotgenerator
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  async: ^2.13.0
  fixnum: ^1.1.1
  io: ^1.0.5
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
